WhiteBoardDemo/Controllers/RoomsController.cs
using Microsoft.AspNet.SignalR;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WhiteBoardDemo.Hubs;
using WhiteBoardDemo.Models;
using WhiteBoardDemo.Services;

namespace WhiteBoardDemo.Controllers
{
    [System.Web.Mvc.Authorize]
    public class RoomsController : Controller
    {

        private readonly IRoomsService _IRoomsService;

        public RoomsController()
        {
            _IRoomsService = new RoomsService(new ApplicationDbContext());
        }

        //private ApplicationDbContext db = new ApplicationDbContext();


        public ActionResult Index()
        {
            return View(_IRoomsService.GetAllRooms());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = _IRoomsService.GetRoomById(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            IEnumerable<Message> RoomMessages = _IRoomsService.GetRoomMessages(id);
            RoomViewModel roomvm = new RoomViewModel { Id = room.Id, RoomName = room.RoomName, Messages = RoomMessages };
            if (room.WhiteboardData != null)
            {
                var base64String = Convert.ToBase64String(room.WhiteboardData);
                var dataUrl = $"data:image/png;base64,{base64String}";
                roomvm.WhiteboardData = dataUrl;

            }

            return View(roomvm);
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RoomName")] Room room)
        {
            if (ModelState.IsValid)
            {
                var hubContext = GlobalHost.ConnectionManager.GetHubContext<WhiteboardHub>();
                _IRoomsService.CreateRoom(room);
                hubContext.Clients.All.createRoom(room);
                return RedirectToAction("Details", room);
            }

            return View(room);
        }

        public ActionResult Join(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = _IRoomsService.GetRoomById(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            _IRoomsService.AddRoomMember(room, HttpContext.User.Identity.Name);
            return RedirectToAction("Details", room);

        }
        public ActionResult Leave(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = _IRoomsService.GetRoomById(id);
            if (room == null)
            {
                return HttpNotFound();
            }

            _IRoomsService.LeaveRoom(id, HttpContext.User.Identity.Name);
            return RedirectToAction("Index");

        }



        // GET: Rooms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = _IRoomsService.GetRoomById(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _IRoomsService.RemoveRoom(id);
            return RedirectToAction("Index");
        }

   
    }
}

WhiteBoardDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <style>
        a {
            color:white;
        }
    </style>
    @*@Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@

    @Scripts.Render("~/bundles/jquery")

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.3.js"></script>
    <script src="~/signalr/hubs"></script>
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top" style="color:white;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Meetings App", "Index", "Rooms", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Rooms", "Index", "Rooms")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>


    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>